spring:
  profiles:
    active: home

---
spring:
  profiles: home
  datasource:
    url: jdbc:mysql://192.168.1.119:3306/springboot_cache?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.1.119
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#debug: true

---

spring:
  profiles: company
  datasource:
    url: jdbc:mysql://192.168.2.107:3306/springboot_cache?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.2.107
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#debug: true