spring:
  profiles:
    active: company

---
spring:
  profiles: home
  elasticsearch:
    jest:
      uris: http://192.168.1.119:9200/
  data:
      elasticsearch:
        cluster-name: elasticsearch
        cluster-nodes: 192.168.1.119:9300

---

spring:
  profiles: company
  elasticsearch:
    jest:
      uris: http://192.168.2.107:9200/
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.2.107:9300