spring:
  profiles:
    active: company

---
spring:
  profiles: home
  rabbitmq:
    host: 192.168.2.107
    port: 5672
    username: guest
    password: guest

---

spring:
  profiles: company
  rabbitmq:
    host: 192.168.2.107
    port: 5672
    username: guest
    password: guest